[package]
name = "v-message"
version = "2.4.0"
description = "V-Message Desktop Application"
authors = ["V-Message Team"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true

# Указываем что src находится в src-tauri/src
[lib]
name = "v_message_lib"
path = "src/main.rs"
crate-type = ["lib"]

[[bin]]
name = "v-message"
path = "src/main.rs"
